# Generated by Django 3.1.2 on 2021-02-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20210208_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparto',
            name='dia',
        ),
    ]
