# Generated by Django 3.1.2 on 2021-02-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_reparto_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='dia',
            field=models.DateField(null=True),
        ),
    ]
